[package]
name = "sl-bwx"
version = "0.1.0"
edition = "2021"

[lib]
name = "bwx"

[dependencies]
byteorder = "1.4.3"
tracing = "0.1.32"
encoding_rs = "0.8.30"
ron = "0.7.0"
json5 = "0.4.1"
serde = { version = "1", features = ["derive"] }
cgmath = "0.18.0"
