[package]
name = "sl_asset"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
encoding_rs = "0.8.30"
gltf = "1.0.0"
image = "0.24.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
tracing = "0.1.32"
